spin_manifest_version = 2

[application]
authors = ["vamshireddy <vamshiproject02@gmail.com>"]
description = ""
name = "11ty-spin"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "11ty-spin"

[component.11ty-spin]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "../public", destination = "/" }]
exclude_files = ["**/node_modules"]

[component.11ty-spin.build]
command = "npm run build"